name: 'max/best'
cls:
  _target_: ensemble_annotations.max.MaxEnsemble

labelling_functions:
  - /home/sasce/PycharmProjects/CodeGraphClassification/data/processed/annotations/keyword/identifiers/yake/none/JSDivergence/0.5/
  - /home/sasce/PycharmProjects/CodeGraphClassification/data/processed/annotations/keyword/name/yake/none/none
