_target_: src.data.datamodule.GitRankingDataModule
graph_dir: "/home/sasce/PycharmProjects/CodeGraphClassification/data/interim/arcanOutput"
feature_dir: "/home/sasce/PycharmProjects/CodeGraphClassification/data/processed/embedding/name/fastText"
out_dir: "/home/sasce/PycharmProjects/CodeGraphClassification/data/processed/torch"
embedding_size: 300
batch_size: 1024
num_splits: ${num_splits}
split: ${split}